### PR TITLE
Fix 3 problems of GlobalTransactionScanner class

### PR DESCRIPTION
**Pull request by tswstarplanet**
1.Fix the problem of duplicate assign new instance of field 'interceptor'
2.Remove the unnecessary type parameter
3.Let static field 'PROXYED_SET' just contains the names of object of class that has methods annotated by @GlobalTransactional

### CODE REVIEW

**Comment by slievrly** [comment]
@tswstarplanet you should proposal an PR

**Comment by slievrly** [comment]
@tswstarplanet please review f933140ab87d951df1f8253652cc949452609a2e

**Comment by tswstarplanet** [comment]
@slievrly What do you mean ? Isn’t this a pr?

**Comment by slievrly** [comment]
image

**Comment by slievrly** [comment]
@tswstarplanet

**Comment by slievrly** [comment]
can DingTalk @清铭

**Comment by tswstarplanet** [comment]
Sorry I can’t find you with nickname “清铭” in dingtalk

**Comment by slievrly** [comment]
image

**Comment by slievrly** [comment]
@tswstarplanet

**Comment by tswstarplanet** [comment]
But if we don’t move the line of code, it seems every bean wired by spring will be added to the set. Maybe we can move the line of code after the else clause?

**Comment by slievrly** [comment]
> But if we don’t move the line of code, it seems every bean wired by spring will be added to the set. Maybe we can move the line of code after the else clause?

Just to judge whether it has been proxyed by fescar

**Comment by tswstarplanet** [comment]
I hava pushed a commit again, would you please see if it is right now?

**Pull request merged**
