### PR TITLE
Delete extra semicolons

### PR DESCRIPTION
**Pull request by systp**
Delete extra semicolons

### CODE REVIEW

**Comment by slievrly** [comment]
forbid CHS comment

**Comment by systp** [comment]
> 禁止CHS评论

Ok, I will pay attention to it later.

**Comment by systp** [comment]
> 禁止CHS评论

Hello, may I ask if I need to resubmit?

**Comment by slievrly** [comment]
@systp I will close this PR, please resubmit.

**Comment by systp** [comment]
> @systp我将关闭此PR，请重新提交。

OK Thank you

**Pull request closed without merging**
