### PR TITLE
fix threadLocal variables leak problems of GlobalTransactionContext

### PR DESCRIPTION
**Pull request by tankilo**
### Ⅰ. Describe what this PR did
call GlobalTransactionContext#clean in TransactionalTemplate#execute   if the  GlobalTransaction is not an existing transaction

### Ⅱ. Does this pull request fix one issue?
https://github.com/alibaba/fescar/issues/313

### CODE REVIEW

**Comment by tankilo** [comment]
image
Firstly, what does the above `self-requested a review` means? 
I thought you will review and edit this pull request yourself. So i did't do anythings.

I noticed that you correct this problem by yourself instead of merging mine.
https://github.com/alibaba/fescar/issues/325

But it seems that you ignore something that i contained in this pull request, your change will cause problems in nested transactions scene. I will comment on https://github.com/alibaba/fescar/issues/313 later.

**Comment by slievrly** [comment]
it has been fixed

**Comment by sharajava** [comment]
I just proposed another fix: https://github.com/alibaba/fescar/pull/354

Would you please join the review? I think GlobalTransaction instance storing in thread local seems not a necessary mechanism.

**Comment by tankilo** [comment]
> I just proposed another fix: #354
> 
> Would you please join the review? I think GlobalTransaction instance storing in thread local seems not a necessary mechanism.

I've read it and didn't see any problem.

**Pull request closed without merging**
