### PR TITLE
 remove redundant class in common module

### PR DESCRIPTION
**Pull request by yuan**
### Ⅰ. Describe what this PR did
In fescar-comom module,  RejectedPolicys.java is redundant, so remove it.

### CODE REVIEW

**Comment by yuan** [comment]
It seems that this problem has been solved, please ignore this pr e_e

**Comment by slievrly** [comment]
> It seems that this problem has been solved, please ignore this pr e_e

not solve，please get latest code

**Comment by slievrly** [comment]
should delete two files

**Comment by yuan** [comment]
> should delete two files

You are right, you should close this pr. Sorry for the touble

**Comment by slievrly** [comment]
> > should delete two files
> 
> You are right, you should close this pr. Sorry for the touble

reopen a pr?

**Comment by yuan** [comment]
> > > should delete two files
> > 
> > 
> > You are right, you should close this pr. Sorry for the touble
> 
> reopen a pr?

no, you can remove file directly

**Comment by slievrly** [comment]
> > > > should delete two files
> > > 
> > > 
> > > You are right, you should close this pr. Sorry for the touble
> > 
> > 
> > reopen a pr?
> 
> no, you can remove file directly

if remove directly it will be not in a pr

**Pull request closed without merging**
