### PR TITLE
config instance obtained by the factory class

### PR DESCRIPTION
**Pull request by quyc07**

### CODE REVIEW

**Comment by slievrly** [comment]
@quyc07 forbid CHS comment and check your code style

**Comment by quyc07** [comment]
> 
> 
> @quyc07 forbid CHS comment and check your code style

ok, the second commit was a mistake, I just wanted to commit it to my branch

**Comment by slievrly** [comment]
@quyc07 I will close this PR, and you should pull request to alibaba/fescar:develop

**Comment by quyc07** [comment]
> 
> 
> @quyc07 I will close this PR, and you should pull request to alibaba/fescar:develop

ok, thanks

**Pull request closed without merging**
