### PR TITLE
fix applicationIdMap may be null

### PR DESCRIPTION
**Pull request by guixincui**
- bugfix : applicationIdMap may be null

### CODE REVIEW

**Comment by xingfudeshi** [comment]
Can you give a short explain how to re-produce this bug?

**Comment by guixincui** [comment]
signed

**Comment by guixincui** [comment]
> Can you give a short explain how to re-produce this bug?
I start then fescar-server  in '/Users/cuigx/tools/fescar', when debug fescar-samples, it generate a file 'root.data',  and mysql undo_log generate new rollback_info.
when fescar-server restart  it throws null pointer exception

**Comment by xingfudeshi** [comment]
> > Can you give a short explain how to re-produce this bug?
> > Startup  fescar-server  in '/Users/cuigx/tools/fescar' and then debug fescar-samples, it generate a file 'root.data',  and mysql undo_log generate new rollback_info.
> > and then when fescar-server restart  it throws null pointer exception

ok,i will check.

**Pull request merged**
